services:
  iwkits-client:
    container_name: iwkits-client
    hostname: iwkits-client
    image: dev.kitstech.local/iw-kits/client:latest
    networks:
      - iwkits-network
    depends_on:
      - iwkits-api
    ports:
      - "3000:80"

  iwkits-api:
    container_name: iwkits-api
    hostname: iwkits-api
    image: dev.kitstech.local/iw-kits/api:latest
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft=Warning
      - securityTokens__jwtKey=${SECURITY_TOKENS_JWT_KEY}
      - mongodbOptions__connectionString=${MONGODB_OPTIONS_CONNECTION_STRING}
      - mongodbOptions__databaseName=${MONGODB_OPTIONS_DATABASE_NAME}
    networks:
      - iwkits-network
    depends_on:
      - iwkits-db
    ports:
      - "5152:8080"

  iwkits-db:
    container_name: iwkits-db
    hostname: iwkits-db
    image: mongo:latest
    command: mongod --auth
    networks:
      - iwkits-network
    ports:
      - "27017:27017"
    volumes:
      - "iwkits-data:/data/db"

networks:
  iwkits-network:
    name: iwkits-network
    driver: bridge

volumes:
  iwkits-data:
    name: iwkits-data
    driver: local
    driver_opts:
      type: none
      device: ./mongodb
      o: bind